# Generated by Django 4.1.2 on 2022-10-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miembro',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='miembro',
            name='color_fav',
        ),
        migrations.AddField(
            model_name='miembro',
            name='edad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='miembro',
            name='fecha_nac',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
